export default {
  colors: {
    bgPrimary: '#0A0A0F',
    bgSecondary: '#0E0E1A',
    bgTertiary: '#161625',
    accentMagenta: '#E91E8C',
    accentViolet: '#7C3AED',
    accentCyan: '#00E5FF',
    accentGold: '#C9A84C',
    accentGoldLight: '#F5D27A',
    accentRed: '#FF3B6B',
    accentGreen: '#2DFF93',
    textPrimary: '#FFFFFF',
    textSecondary: '#9B9BC0',
    textMuted: '#4A4A6A',
    borderGlass: 'rgba(255,255,255,0.06)',
    overlayDark: 'rgba(10,10,15,0.95)',
  },
  gradients: {
    primary: ['#E91E8C', '#7C3AED'],
    glow: ['#00E5FF', '#7C3AED'],
    gold: ['#C9A84C', '#F5D27A', '#C9A84C'],
  },
  typography: {
    fontDisplay: 'Clash Display',
    fontBody: 'Inter',
    fontMono: 'monospace',
    sizeDisplay: 32,
    sizeH1: 24,
    sizeH2: 18,
    sizeBody: 14,
    sizeLabel: 12,
    sizeMonoLg: 20,
    sizeMonoSm: 13,
  },
  shadow: {
    glowMagenta: { shadowColor: '#E91E8C', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 12, elevation: 8 },
    glowViolet: { shadowColor: '#7C3AED', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 12, elevation: 8 },
    glowCyan: { shadowColor: '#00E5FF', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 8, elevation: 5 },
    glowGold: { shadowColor: '#C9A84C', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 10, elevation: 6 },
    glowRed: { shadowColor: '#FF3B6B', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 12, elevation: 8 },
    glowGreen: { shadowColor: '#2DFF93', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 10, elevation: 6 },
    glass: { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 10, elevation: 5 },
  },
  spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32, xxl: 48 },
  radius: { sm: 10, md: 16, lg: 20, xl: 28, pill: 999 },
};