export default {
  colors: {
    bgPrimary: '#0A0A0F',
    bgSecondary: '#12121A',
    bgTertiary: '#1A1A28',
    accentMagenta: '#FF2D78',
    accentViolet: '#8B2FF8',
    accentCyan: '#00E5FF',
    accentRed: '#FF3040',
    accentGreen: '#2DFF93',
    textPrimary: '#FFFFFF',
    textSecondary: '#A0A0B8',
    textMuted: '#4A4A6A',
    borderGlass: 'rgba(255,255,255,0.08)',
    overlayDark: 'rgba(10,10,15,0.85)',
  },
  typography: {
    fontDisplay: 'sans-serif-condensed',
    fontBody: 'sans-serif',
    fontMono: 'monospace',
    sizeDisplay: 32,
    sizeH1: 24,
    sizeH2: 18,
    sizeBody: 14,
    sizeLabel: 12,
    sizeMonoLg: 20,
    sizeMonoSm: 13,
  },
  shadow: {
    glowMagenta: { shadowColor: '#FF2D78', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 12, elevation: 8 },
    glowViolet: { shadowColor: '#8B2FF8', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 12, elevation: 8 },
    glowCyan: { shadowColor: '#00E5FF', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 8, elevation: 5 },
    glowRed: { shadowColor: '#FF3040', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 12, elevation: 8 },
    glowGreen: { shadowColor: '#2DFF93', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.6, shadowRadius: 10, elevation: 6 },
    glass: { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 10, elevation: 5 },
  },
  spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32, xxl: 48 },
  radius: { sm: 10, md: 16, lg: 20, xl: 28, pill: 999 },
};